server:
  port: 9021
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9003/eureka/
  instance:
  # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
spring:
  boot:
    admin:
      client:
        url: http://localhost:9001
  application:
    name: provider-crm