server:
  port: 9003
spring:
  application:
    name: eureka-server
  boot:
    admin:
      client:
        url: http://localhost:9001
eureka:
  client:
    register-with-eureka: false
    service-url:
      # 指定eureka server的通信地址
      defaultZone: http://localhost:${server.port}/eureka
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
