server:
  port: 9020

spring:
  boot:
    admin:
      client:
        url: http://localhost:9001
  application:
    name: @pom.artifactId@
  profiles:
    active: dev
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:mysql://localhost:3306/oops_crm?zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456