server:
  port: 7005
spring:
  application:
    name: @pom.artifactId@
  profiles:
    active: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

