server:
  port: 7005
spring:
  application:
    name: @pom.artifactId@
  profiles:
    active: master
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
